apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: development
  labels:
    app: simple-crud
    component: api
    environment: development
spec:
  selector:
    matchLabels:
      app: simple-crud
      component: api
      environment: development
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-crud
        component: api
        environment: development
    spec:
      containers:
        - name: api
          image: dosquisd/simple_crud:latest
          env:
            # PostgreSQL environment variables
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-config
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgres-config
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: postgres-config
            # Redis environment variables
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST
                  name: redis-config
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: redis-config
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASSWORD
                  name: redis-secret

            # Environment variables for the API
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: api-secret
            - name: DEBUG
              value: "false"

            # QuestDB environment variables
            - name: QUESTDB_HOST
              valueFrom:
                configMapKeyRef:
                  key: QUESTDB_HOST
                  name: questdb-config
            - name: QUESTDB_PORT
              valueFrom:
                configMapKeyRef:
                  key: QUESTDB_PORT
                  name: questdb-config
            - name: QUESTDB_USER
              valueFrom:
                configMapKeyRef:
                  key: QDB_PG_USER
                  name: questdb-config
            - name: QUESTDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: QUESTDB_PASSWORD
                  name: questdb-secret
            - name: QUESTDB_PG_PORT
              valueFrom:
                configMapKeyRef:
                  key: QUESTDB_PG_PORT
                  name: questdb-config
            - name: QUESTDB_DB
              valueFrom:
                configMapKeyRef:
                  key: QUESTDB_DB
                  name: questdb-config

          ports:
            - containerPort: 8000

          # Health checks
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          # Resources
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
